<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>DayZRoadBuilder.Cli</RootNamespace>
    <AssemblyName>DayZRoadBuilder.Cli</AssemblyName>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DayZRoadBuilder.Core\DayZRoadBuilder.Core.csproj" />
  </ItemGroup>

</Project>
